spring.application.name=infinito-security

spring.datasource.url=jdbc:postgresql://localhost:5432/controlneg_rmx_db?currentSchema=security
spring.datasource.username=romax-admin
spring.datasource.password=f4ast3rv3rs10n*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=security

# JWT properties
jwt.secret=ht0tS/H4Nw~'3rZ?rg{A7rNQ!%qW}Hjf]YOBN,Us,)B:fxO9u$:-a$(v7"g&zbw
jwt.expiration-days=7

# Puerto del servidor
server.port=8081

# Inicialización de SQL (asegurar ejecución de schema.sql y data.sql en PostgreSQL no embebido)
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql
# Permitir continuar si CREATE EXTENSION no tiene permisos en el entorno
spring.sql.init.continue-on-error=true

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# Servicio externo de envío de correos
mail.service.url=http://localhost:8082/api/v1/mail/send
