spring.application.name=infinito-security

spring.datasource.url=jdbc:postgresql://localhost:5432/controlneg_rmx_db?currentSchema=security
spring.datasource.username=romax-admin
spring.datasource.password=f4ast3rv3rs10n*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=security
